name: x_mansion
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  # Riverpod
  riverpod: ^2.1.3
  flutter_riverpod: ^2.1.3
  hooks_riverpod: ^2.1.3

  # firebase
  firebase_core: ^2.4.0
  cloud_firestore: ^4.3.0

  # auto-route
  auto_route: ^5.0.4

  #media
  flutter_svg: ^1.1.6

  #theme
  google_fonts: ^3.0.1



  dartz: ^0.10.1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.7.0

  #form :v â™¥
  flutter_form_builder: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  freezed: ^2.0.3
  auto_route_generator: ^5.0.2
  lints: ^2.0.0
  test: ^1.16.0

flutter:
  uses-material-design: true
  assets: 
  - assets/

